### ISSUE TITLE
dsbdriverd not loading iwn device firmware on 12.0-RELEASE

### ISSUE THREAD

**Issue by pkgdemon** [mrclksr/DSBDriverd#1]
Hi,
I wanted to use dsbdriverd for a side project I am working on.  At first I ran into this with a friend, and then I bought a laptop which could replicate a Lenovo T430S.  I was looking at the code for drivers.db and it seems you load if_iwn when a match is found.  However it seems this is not needed with 12.0-RELEASE or higher because the module is already compiled into the kernel.  

https://github.com/freebsd/freebsd/blob/releng/12.0/sys/amd64/conf/GENERIC

Therefore the correct firmware must be loaded or alternatively all firmwares (not ideal) can to be loaded in order to use a device required by the driver which dsbdriverd does not seem to do.  Do you use a custom kernel with iwn removed for NomadBSD so that dsbdriverd can load if_iwn post boot, and hopefully load the modules as well?  If not how does it work for iwn?

**Comment by mrclksr** [comment]
Hi there Joe,

> I was looking at the code for drivers.db and it seems you load if_iwn when a match is found. However it seems this is not needed with 12.0-RELEASE or higher because the module is already compiled into the kernel.

DSBDriverd will only try to load a module if it's not already loaded or compiled into the kernel.

> Therefore the correct firmware must be loaded or alternatively all firmwares (not ideal) can to be loaded in order to use a device required by the driver which dsbdriverd does not seem to do. Do you use a custom kernel with iwn removed for NomadBSD so that dsbdriverd can load if_iwn post boot, and hopefully load the modules as well? If not how does it work for iwn?

Actually, I hadn't added entries for the firmware modules, yet. Thank you for the reminder! Please let me know if dsbdriverd loads the correct firmware modules with the updated drivers DB:

https://github.com/mrclksr/DSBDriverd/commit/fccffb0002e15560ec2cc4be931781a7646b61b4

Pull requests with additions to the database are always welcome :)

**Comment by pkgdemon** [comment]
Awesome.  I will give this a try.  Thank you.

**Comment by pkgdemon** [comment]
Here is the result:

Wed Nov 13 20:26:42 2019: vendor=8086 product=0154 Intel Corporation 3rd Gen Core processor DRAM Controller: No driver found
Wed Nov 13 20:26:42 2019: vendor=8086 product=0166 Intel Corporation 3rd Gen Core processor Graphics Controller: No driver found
Wed Nov 13 20:26:42 2019: vendor=8086 product=1e31 Intel Corporation 7 Series/C210 Series Chipset Family USB xHCI Host Controller: No driver found
Wed Nov 13 20:26:42 2019: vendor=8086 product=1e3a Intel Corporation 7 Series/C216 Chipset Family MEI Controller : No driver found
Wed Nov 13 20:26:42 2019: vendor=8086 product=1e3d Intel Corporation 7 Series/C210 Series Chipset Family KT Controller: No driver found
Wed Nov 13 20:26:42 2019: vendor=8086 product=1502 Intel Corporation 82579LM Gigabit Network Connection (Lewisville): if_em already loaded
Wed Nov 13 20:26:42 2019: vendor=8086 product=1e2d Intel Corporation 7 Series/C216 Chipset Family USB Enhanced Host Controller : No driver found
Wed Nov 13 20:26:42 2019: vendor=8086 product=1e20 Intel Corporation 7 Series/C216 Chipset Family High Definition Audio Controller: snd_hda already loaded
Wed Nov 13 20:26:42 2019: vendor=8086 product=1e10 Intel Corporation 7 Series/C216 Chipset Family PCI Express Root Port 1: No driver found
Wed Nov 13 20:26:42 2019: vendor=8086 product=1e12 Intel Corporation 7 Series/C210 Series Chipset Family PCI Express Root Port 2: No driver found
Wed Nov 13 20:26:42 2019: vendor=8086 product=1e14 Intel Corporation 7 Series/C210 Series Chipset Family PCI Express Root Port 3: No driver found
Wed Nov 13 20:26:42 2019: vendor=8086 product=1e26 Intel Corporation 7 Series/C216 Chipset Family USB Enhanced Host Controller : No driver found
Wed Nov 13 20:26:42 2019: vendor=8086 product=1e55 Intel Corporation QM77 Express Chipset LPC Controller: ichwd already loaded
Wed Nov 13 20:26:42 2019: vendor=8086 product=1e03 Intel Corporation 7 Series Chipset Family 6-port SATA Controller [AHCI mode]: No driver found
Wed Nov 13 20:26:42 2019: vendor=8086 product=1e22 Intel Corporation 7 Series/C216 Chipset Family SMBus Controller: No driver found
Wed Nov 13 20:26:43 2019: vendor=8086 product=0085 Intel Corporation Centrino Advanced-N 6205 [Taylor Peak] Centrino Advanced-N 6205 (802.11a/b/g/n): if_iwn already loaded
Wed Nov 13 20:26:43 2019: vendor=1180 product=e823 Ricoh Co Ltd PCIe SDXC/MMC Host Controller: No driver found
Wed Nov 13 20:26:43 2019: vendor=0000 product=0000 21  HID: No driver found
Wed Nov 13 20:26:43 2019: vendor=8087 product=0024 Intel Corp. Integrated Rate Matching Hub: No driver found
Wed Nov 13 20:26:43 2019: vendor=1f75 product=0917 Innostor Technology Corporation: umass already loaded
Wed Nov 13 20:26:43 2019: vendor=147e product=2020 Upek TouchChip Fingerprint Coprocessor (WBF advanced mode): No driver found
Wed Nov 13 20:26:43 2019: vendor=0a5c product=21e6 Broadcom Corp. BCM20702 Bluetooth 4.0 [ThinkPad]: No driver found
Wed Nov 13 20:26:43 2019: vendor=04f2 product=b2da Chicony Electronics Co., Ltd thinkpad t430s camera: No driver found

**Comment by mrclksr** [comment]
The subdevice IDs slipped into the subvendor column:
https://github.com/mrclksr/DSBDriverd/commit/30029d46ef4c24e019fd7f2c3db2779dfb8f08b0

**Comment by pkgdemon** [comment]
Still not working.  Same result where it only tries to load if_iwn.  I tried removing that locally but it still didn't move on to firmware.  Is there anything else I can provide like pciconf output to help?  I don't think the trick of using * is working to use any subvendor id?

**Comment by pkgdemon** [comment]
If it helps this is the specific firmware that I need for my chipset:

```
iwn6000g2afw
	8086
		0082
			*
				1301
				1306
				1307
				1321
				1326
				1311
				1316
				C020
				C220
				4820
				1304
				1305
		0085
			*
				1301
				1306
				1307
				1321
				1326
				1311
				1316
				C020
				C220
				4820
				1304
				1305
```
I can see how 8086 corresponds to ```pciconf -lv | grep -A1 -B3 network``` output for card, and chip.  But what do the other numbers under 8086 correspond too?  Class? Rev?  Something else outside of output pciconf would provide?

**Comment by pkgdemon** [comment]
Oh nevermind, you documented here:

```
# driver_module1 [driver_module2 ...]
#	vendor					<-- One tab
#		device [extra info]		<-- Two tabs
#			subvendor		<-- Three tabs
#				subdevice	<-- Four tabs
```

**Comment by pkgdemon** [comment]
Ok so after a bit of research I just learned about ```devinfo -v``` and found all the info i needed.  I think I am a little closer to understanding how drivers.db works.  

I tried this:

```
iwn6000g2afw
	8086
		0082
			*
				1301
				1306
				1307
				1321
				1326
				1311
				1316
				C020
				C220
				4820
				1304
				1305
		0085
			8086
				1301
				1306
				1307
				1321
				1326
				1311
				1316
				C020
				C220
				4820
				1304
				1305
```

My subvendor is 8086 just like vendor which are both 8086 with ```devinfo -v``` output.  The device is 0085, subdevice is 1311, class is 8000 in case any of this is helpful.

**Comment by mrclksr** [comment]
There was a bug in the parser algorithm. Please checkout https://github.com/mrclksr/DSBDriverd/commit/44205bc719c0d8f4ed9517503756639597bd9f10.

**Comment by pkgdemon** [comment]
Working now.  Thank you very much.

**Comment by mrclksr** [comment]
Excellent!
